# Preparando_recursos_e_rotulos

In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

Printar intervalo de 10 valores

In [3]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


Expandir o dataset usando janelas(window)

In [8]:
dataset = tf.data.Dataset.range(10)
# 5 = tamanho da janela e shift=1 o quanto quer deslocar a cada vez
dataset = dataset.window(5,shift=1)
for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [11]:
dataset = tf.data.Dataset.range(10)
#Como chega no final vai acabando dados, adiciona o drop para ter dados dimensionados
dataset = dataset.window(5,shift=1, drop_remainder=True)
for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [12]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
for window in dataset:
    #troca por print(window.numpy()) para adicionar em uma lista numpy para usar em ML
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


Dividir em recursos e rotulos 
Features and Labels

In [14]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
#o último pode ser o recurso(windows[:-1])/ ultimo valor da lista e o último pode ser o rótulo(window[-1:]) que denota tudo sobre o ultimo valor
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
    print(x.numpy(), y.numpy())
#x = features = recursos (valores alteriores)
#y = labels = rotulos (atual)

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


Embaralhar os dados de treinamento
Importante para não se colocar um vies nos dados

In [15]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
#shuffle = embaralha os dados. 10 porque é a quantidade de dados q temos
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
    print(x.numpy(), y.numpy())
#x = features = recursos
#y = labels = rotulos

[5 6 7 8] [9]
[0 1 2 3] [4]
[1 2 3 4] [5]
[4 5 6 7] [8]
[3 4 5 6] [7]
[2 3 4 5] [6]


In [17]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5,shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
#batch que separa em tamanho 2 / Agrupamento em numero de dois
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
    print("x =", x.numpy())
    print("y =", y.numpy())

x = [[3 4 5 6]
 [4 5 6 7]]
y = [[7]
 [8]]
x = [[5 6 7 8]
 [1 2 3 4]]
y = [[9]
 [5]]
x = [[0 1 2 3]
 [2 3 4 5]]
y = [[4]
 [6]]
